import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { speedDialButton } from "./speedDialItems";
const IconButton = ({ iconPath, label }) => {
    return (_jsx(_Fragment, { children: _jsxs("div", { className: "relative", children: [_jsxs("button", { type: "button", className: "flex h-[52px] w-[52px] items-center justify-center rounded-lg border peer/hover border-gray-200 bg-white text-gray-500 shadow-sm hover:bg-gray-50 hover:text-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white dark:focus:ring-gray-400", children: [_jsx("svg", { className: "h-5 w-5", xmlns: "http://www.w3.org/2000/svg", fill: "currentColor", viewBox: "0 0 20 20", children: _jsx("path", { d: iconPath }) }), _jsx("span", { className: "sr-only", children: label })] }), _jsx("div", { className: "tooltip invisible absolute z-10 inline-block w-auto rounded-lg bg-gray-900 px-3 py-2 text-sm font-medium text-white opacity-0 shadow-sm transition-opacity duration-300 dark:bg-gray-700 group-hover:visible peer-hover/hover:opacity-100", children: label })] }) }));
};
const SpeedDial = () => {
    return (_jsx(_Fragment, { children: _jsxs("div", { className: "group fixed bottom-6 end-6 z-50", children: [_jsx("div", { className: "mb-4 hidden flex-col items-center space-y-2 group-hover:flex", children: speedDialButton.map((button, index) => (_jsx(IconButton, { iconPath: button.iconPath, label: button.label }, index))) }), _jsxs("button", { type: "button", className: "flex h-14 w-14 items-center justify-center rounded-lg bg-blue-700 text-white hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800", children: [_jsx("svg", { className: "h-5 w-5 transition-transform group-hover:rotate-45", xmlns: "http://www.w3.org/2000/svg", fill: "none", viewBox: "0 0 18 18", children: _jsx("path", { stroke: "currentColor", strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M9 1v16M1 9h16" }) }), _jsx("span", { className: "sr-only", children: "Open actions menu" })] })] }) }));
};
export default SpeedDial;
