import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useCartContext } from "@contexts/CartContext";
import StripePopup from "@services/Strippe/Strippe";
import * as React from "react";
function OrderItem() {
    const [OptionValue, setOptionValue] = React.useState(0);
    const [totalPrice, settotalPrice] = React.useState(0);
    const [isChecked, setIsChecked] = React.useState(false);
    const [noticeError, setnoticeError] = React.useState(false);
    const src = "https://product.hstatic.net/1000312752/product/09a661c8a5a5aec10a8fc85c77d6416b069f4b1091662927387f7bb38624078f777ed3_acafc873ad214e18af6e481d53ada1e8.jpg";
    const cartContext = useCartContext();
    const handlerSumit = (e) => {
        e.preventDefault;
        if (isChecked) {
        }
        setIsChecked(true);
    };
    const handlerSubmit = () => { };
    return (_jsx(_Fragment, { children: _jsxs("div", { className: "flex justify-around m-9", children: [_jsxs("div", { className: "relative overflow-x-auto shadow-md sm:rounded-lg w-1/2 ", children: [_jsx("h1", { className: "title text-center font-semibold", children: "Order Item" }), _jsx("table", { className: "w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400 border-1", children: _jsxs("tbody", { children: [cartContext.getItem()?.map((items) => (console.log(items),
                                        (_jsxs("tr", { className: "bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600 w-full", children: [_jsx("td", { className: "p-4", children: _jsx("img", { src: import.meta.env.VITE_API_URL +
                                                            "/uploads/", className: "w-16 md:w-32 max-w-full max-h-full", alt: "Apple Watch" }) }), _jsx("td", { className: "px-6 py-4 font-semibold text-gray-900 dark:text-white", children: items.name }), _jsx("td", { className: "px-6 py-4", children: _jsx("div", { className: "flex items-center", children: _jsx("div", { children: _jsx("input", { type: "number", id: "first_product", className: "bg-gray-50 w-14 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block px-2.5 py-1 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder: "1", readOnly: true }) }) }) }), _jsx("td", { className: "px-6 py-4 font-semibold text-gray-900 dark:text-white", children: items.base_price ? items.base_price : 0 }), _jsx("td", { className: "px-6 py-4", children: _jsx("button", { type: "submit", className: "font-medium  dark:text-red-500 border-2 p-4 rounded-xl hover:bg-red-400", onClick: () => {
                                                            cartContext.removeFromCart(items.id);
                                                        }, children: "Remove" }) })] })))), _jsxs("tr", { className: "bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600 w-full", children: [_jsx("td", { className: "p-4", children: _jsx("img", { src: src, className: "w-16 md:w-32 max-w-full max-h-full", alt: "Apple Watch" }) }), _jsx("td", { className: "px-6 py-4 font-semibold text-gray-900 dark:text-white", children: "Apple Watch" }), _jsx("td", { className: "px-6 py-4", children: _jsx("div", { className: "flex items-center", children: _jsx("div", { children: _jsx("input", { type: "number", id: "first_product", className: "bg-gray-50 w-14 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block px-2.5 py-1 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder: "1", readOnly: true }) }) }) }), _jsx("td", { className: "px-6 py-4 font-semibold text-gray-900 dark:text-white", children: "$599" }), _jsx("td", { className: "px-6 py-4", children: _jsx("button", { type: "submit", className: "font-medium  dark:text-red-500 border-2 p-4 rounded-xl hover:bg-red-400", onClick: () => {
                                                        cartContext.removeFromCart(1);
                                                    }, children: "Remove" }) })] })] }) })] }), _jsx("div", { className: "FormPayMent w-1/3", children: _jsxs("form", { className: "mx-auto max-w-sm", onSubmit: (e) => handlerSumit(e), children: [_jsxs("div", { className: "mb-5", children: [_jsx("label", { htmlFor: "email", className: "mb-2 block text-sm font-medium text-gray-900 dark:text-white", children: "Your email" }), _jsx("input", { type: "email", id: "email", className: "dark:shadow-sm-light block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 shadow-sm focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500", placeholder: "example@gmail.com", required: true })] }), _jsxs("div", { className: "mb-5", children: [_jsx("label", { htmlFor: "password", className: "mb-2 block text-sm font-medium text-gray-900 dark:text-white", children: "Total Price" }), _jsx("input", { type: "text", id: "password", className: "dark:shadow-sm-light block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 shadow-sm focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500", value: "$5990", disabled: true })] }), _jsxs("div", { className: "mb-5", children: [_jsx("label", { htmlFor: "method", className: "mb-2 block text-sm font-medium text-gray-900 dark:text-white", children: "Select Payment Method" }), _jsxs("select", { id: "method", name: "method", onChange: (e) => setOptionValue(Number(e.target.value)), value: OptionValue, className: "dark:shadow-sm-light block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 shadow-sm focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500", children: [_jsx("option", { value: 1, className: "rounded-lg", children: "Card" }), _jsx("option", { value: 0, className: "rounded-lg", children: "QRcode" })] })] }), OptionValue == 1 ? (_jsx(_Fragment, { children: _jsx(StripePopup, {}) })) : (_jsx(_Fragment, {})), _jsxs("div", { className: "mb-5 flex items-start", children: [_jsx("div", { className: "flex h-5 items-center", children: _jsx("input", { id: "terms", type: "checkbox", value: "", onChange: (e) => {
                                                setIsChecked(e.target.checked);
                                            }, className: "focus:ring-3 h-4 w-4 rounded border border-gray-300 bg-gray-50 focus:ring-blue-300 dark:border-gray-600 dark:bg-gray-700 dark:ring-offset-gray-800 dark:focus:ring-blue-600 dark:focus:ring-offset-gray-800", required: true }) }), _jsxs("label", { htmlFor: "terms", className: "ms-2 text-sm font-medium text-gray-900 dark:text-gray-300", children: ["I agree with the", " ", _jsx("a", { href: "#", className: "text-blue-600 hover:underline dark:text-blue-500", children: "terms and conditions" })] })] }), _jsx("button", { type: "submit", onClick: () => setnoticeError(true), className: "rounded-lg bg-blue-700 px-5 py-2.5 text-center text-sm font-medium text-white hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800", children: "Submit for Payment" })] }) })] }) }));
}
export default OrderItem;
